when:
  branch: main
  event: [push, manual]

steps:
  deploy:
    image: docker/compose:alpine-1.29.2
    environment:
      VOLUME_PATH:
        from_secret: VOLUME_PATH
    commands:
      - docker-compose up -d --build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
