when:
  branch: main

steps:
  deploy:
    image: docker/compose:alpine-1.29.2
    environment:
      - VOLUME_PATH=$VOLUME_PATH
    commands:
      - docker-compose up -d --build
    secrets: [volume_path]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
