export const order = {
  1: ["LC", "MB", "WC", "BP", "BC", "DDD", "DDJ", "MCR", "DKM", "WS", "PB", "MCT", "YC", "SL", "DC", "RR"],
  2: ["LC", "PB", "DC", "DDD", "DDJ", "MCT", "MB", "DKM", "WC", "BP", "BC", "WS", "SL", "MCR", "YC", "RR"],
  3: ["LC", "YC", "DDD", "BC", "SL", "WC", "DDJ", "PB", "WS", "MB", "MCR", "BP", "MCT", "DKM", "DC", "RR"],
  4: ["LC", "PB", "WS", "DDD", "SL", "BP", "MB", "MCR", "BC", "DKM", "WC", "MCT", "DDJ", "YC", "DC", "RR"],
  5: ["LC", "DDD", "SL", "MCT", "PB", "DKM", "BC", "DDJ", "DC", "MCR", "BP", "WS", "WC", "MB", "YC", "RR"],
  6: ["LC", "MB", "WC", "DC", "BP", "SL", "DKM", "YC", "MCT", "PB", "DDJ", "BC", "WS", "DDD", "MCR", "RR"],
  7: ["LC", "MCR", "WS", "DDJ", "BP", "MCT", "YC", "PB", "WC", "MB", "BC", "DDD", "DKM", "SL", "DC", "RR"],
  8: ["LC", "DC", "WS", "PB", "MCT", "BC", "WC", "YC", "MCR", "BP", "MB", "SL", "DDJ", "DKM", "DDD", "RR"],
  9: ["LC", "DKM", "SL", "DDJ", "PB", "WS", "MB", "DDD", "WC", "MCR", "MCT", "YC", "BP", "DC", "BC", "RR"],
  10: ["LC", "DDD", "BP", "PB", "YC", "WS", "MCR", "DC", "MB", "DKM", "WC", "MCT", "DDJ", "SL", "BC", "RR"],
  11: ["LC", "MCR", "DC", "DKM", "DDD", "DDJ", "YC", "WS", "SL", "MB", "MCT", "BP", "BC", "PB", "WC", "RR"],
  12: ["LC", "DDD", "SL", "MCT", "DKM", "PB", "BP", "MCR", "WC", "MB", "DDJ", "YC", "WS", "PB", "BC", "RR"],
  13: ["LC", "WS", "MCR", "BP", "MB", "DKM", "YC", "MCT", "WC", "DDJ", "PB", "DC", "DDD", "SL", "BC", "RR"],
  14: ["LC", "YC", "MCT", "MB", "WC", "DDD", "BC", "SL", "BP", "MCR", "WS", "PB", "DC", "DKM", "DDJ", "RR"],
  15: ["LC", "SL", "MCR", "BC", "BP", "PB", "WS", "YC", "MB", "DDD", "MCT", "DC", "DDJ", "DKM", "WC", "RR"],
  16: ["LC", "WS", "BP", "DKM", "YC", "MCR", "MB", "DDD", "PB", "MCT", "WC", "SL", "DDJ", "DC", "BC", "RR"],
  17: ["LC", "BP", "DDJ", "DC", "DKM", "WC", "MCT", "YC", "DDD", "WS", "SL", "BC", "MB", "MCR", "PB", "RR"],
  18: ["LC", "BC", "MB", "YC", "WS", "PB", "BP", "MCR", "DKM", "WC", "DDJ", "DC", "SL", "MCR", "DDD", "RR"],
  19: ["LC", "YC", "DDJ", "DC", "MCT", "DDD", "MB", "BC", "MCR", "PB", "WS", "SL", "BP", "DKM", "WC", "RR"],
  20: ["LC", "PB", "WC", "DDJ", "MCT", "DKM", "YC", "MB", "BC", "WS", "DDD", "DC", "MCR", "BP", "SL", "RR"],
  21: ["LC", "MCR", "MCT", "DDD", "WS", "MB", "YC", "DKM", "WC", "PB", "DDJ", "BP", "BC", "DC", "SL", "RR"],
  22: ["LC", "DDD", "DC", "DDJ", "SL", "MCR", "WS", "MCT", "BP", "DKM", "WC", "PB", "MB", "YC", "BC", "RR"],
  23: ["LC", "SL", "DDD", "DC", "DDJ", "BC", "MCT", "MCR", "DKM", "WS", "MB", "BP", "PB", "WC", "YC", "RR"],
  24: ["LC", "MB", "DC", "WC", "YC", "SL", "DDD", "MCR", "BP", "PB", "DDJ", "WS", "DKM", "BC", "MCT", "RR"],
  25: ["LC", "SL", "DDJ", "YC", "BC", "MB", "MCT", "MCR", "PB", "WS", "BP", "DC", "DKM", "WC", "DDD", "RR"],
  26: ["LC", "WC", "MCR", "BC", "DDJ", "SL", "PB", "YC", "BP", "DC", "MB", "DDD", "MCT", "DKM", "WS", "RR"],
  27: ["LC", "DDD", "DKM", "MCR", "DC", "WS", "WC", "MCT", "PB", "BP", "YC", "DDJ", "MB", "SL", "BC", "RR"],
  28: ["LC", "PB", "DC", "DDD", "MB", "DKM", "WC", "WS", "MCT", "DDJ", "SL", "MCR", "YC", "BP", "BC", "RR"],
  29: ["LC", "DKM", "BC", "WS", "DDJ", "MCT", "MCR", "PB", "DDD", "MB", "DC", "SL", "WC", "YC", "BP", "RR"],
  30: ["LC", "MCT", "BP", "DDJ", "DKM", "PB", "MB", "DDD", "YC", "DC", "WS", "SL", "BC", "MCR", "WC", "RR"],
  31: ["LC", "DKM", "BC", "MCR", "MB", "DDD", "MCT", "DC", "PB", "DDJ", "BP", "WS", "SL", "WC", "YC", "RR"],
  32: ["LC", "DC", "YC", "BP", "MB", "DDD", "WC", "MCR", "PB", "BC", "WS", "MCT", "DDJ", "DKM", "SL", "RR"],
  33: ["LC", "MCR", "DDD", "DKM", "DC", "MCT", "WS", "BP", "PB", "MB", "DDJ", "SL", "BC", "YC", "WC", "RR"],
  34: ["LC", "WC", "DC", "MB", "BC", "DDD", "MCR", "PB", "BP", "WS", "SL", "MCT", "YC", "DKM", "DDJ", "RR"],
  35: ["LC", "SL", "WS", "MB", "DDD", "BC", "DDJ", "WC", "YC", "MCR", "PB", "BP", "DC", "MCT", "DKM", "RR"],
  36: ["LC", "DDD", "MCR", "PB", "WC", "MCT", "DC", "WS", "YC", "BP", "MB", "DKM", "DDJ", "SL", "BC", "RR"],
  37: ["LC", "WS", "DC", "DDD", "YC", "MCR", "MB", "DKM", "WC", "DDJ", "PB", "BP", "BC", "MCT", "SL", "RR"],
  38: ["LC", "PB", "DDD", "MCR", "WC", "BP", "MB", "DDJ", "WS", "DKM", "BC", "SL", "MCT", "DC", "YC", "RR"],
  39: ["LC", "DC", "BP", "BC", "WC", "MB", "WS", "YC", "DKM", "PB", "MCT", "DDD", "SL", "MCR", "DDJ", "RR"],
  40: ["LC", "BP", "BC", "WC", "PB", "DDD", "WS", "MCR", "MCT", "MB", "DC", "YC", "DDJ", "SL", "DKM", "RR"],
  41: ["LC", "BC", "MCR", "PB", "DC", "WC", "WS", "YC", "DDJ", "MB", "DDD", "MCT", "SL", "DKM", "BP", "RR"],
  42: ["LC", "YC", "DC", "BC", "MB", "BP", "DKM", "DDD", "PB", "WC", "SL", "WS", "MCR", "MCT", "DDJ", "RR"],
  43: ["LC", "MCT", "PB", "MCR", "BP", "DDJ", "WC", "DDD", "BC", "MB", "DKM", "WS", "SL", "YC", "DC", "RR"],
  44: ["LC", "DKM", "MCR", "DDJ", "SL", "WS", "DC", "DDD", "PB", "MB", "WC", "BP", "YC", "MCT", "BC", "RR"],
  45: ["LC", "SL", "MCR", "BC", "DDJ", "PB", "WC", "DDD", "WS", "BP", "DC", "MCT", "YC", "DKM", "MB", "RR"],
  46: ["LC", "WS", "BP", "DDD", "SL", "MCR", "PB", "DC", "MCT", "DDJ", "MB", "YC", "DKM", "WC", "BC", "RR"],
  47: ["LC", "SL", "MCR", "BC", "YC", "WC", "WS", "MB", "MCT", "DC", "PB", "DDD", "BP", "DKM", "DDJ", "RR"],
  48: ["LC", "MCT", "BC", "DDJ", "PB", "DDD", "DKM", "MCR", "WS", "SL", "MB", "YC", "WC", "DC", "BP", "RR"],
  49: ["LC", "DKM", "MCR", "DDJ", "MCT", "PB", "DDD", "DC", "BP", "SL", "WC", "WS", "YC", "MB", "BC", "RR"],
  50: ["LC", "YC", "DC", "PB", "DKM", "BP", "DDD", "MCR", "MCT", "BC", "MB", "SL", "WC", "WS", "DDJ", "RR"],
  51: ["LC", "WS", "SL", "MCR", "MCT", "MB", "PB", "DDJ", "DKM", "DDD", "DC", "YC", "BC", "BP", "WC", "RR"],
  52: ["LC", "BC", "DKM", "PB", "DC", "YC", "MCT", "MCR", "SL", "DDD", "BP", "MB", "WC", "WS", "DDJ", "RR"],
  53: ["LC", "BP", "MB", "DC", "DDD", "PB", "BC", "YC", "MCR", "WS", "MCT", "SL", "WC", "DKM", "DDJ", "RR"],
  54: ["LC", "MCR", "PB", "DDJ", "MB", "WS", "YC", "DDD", "DKM", "SL", "WC", "BP", "DC", "MCT", "BC", "RR"],
  55: ["LC", "BP", "BC", "YC", "MCT", "PB", "DKM", "DDD", "MB", "WC", "DC", "MCR", "DDJ", "WS", "SL", "RR"],
  56: ["LC", "DDJ", "DC", "PB", "MCR", "DKM", "WS", "MCT", "WC", "DDD", "BP", "YC", "MB", "SL", "BC", "RR"],
  57: ["LC", "DKM", "BC", "DDD", "MCT", "PB", "DC", "WS", "MB", "DDJ", "BP", "MCR", "YC", "SL", "WC", "RR"],
  58: ["LC", "SL", "PB", "BC", "DDJ", "BP", "MCT", "YC", "WS", "WC", "DDD", "MCR", "DC", "DKM", "MB", "RR"],
  59: ["LC", "YC", "DDJ", "PB", "SL", "MB", "DKM", "DDD", "WS", "WC", "DC", "BC", "MCT", "MCR", "BP", "RR"],
  60: ["LC", "YC", "DKM", "MB", "BC", "DDD", "SL", "WC", "PB", "WS", "BP", "MCR", "DDJ", "MCR", "DC", "RR"],
  61: ["LC", "WC", "DDJ", "SL", "PB", "DC", "MB", "DDD", "MCR", "YC", "MCT", "WS", "BP", "BC", "DKM", "RR"],
  62: ["LC", "MB", "DDJ", "YC", "WS", "SL", "WC", "BC", "MCR", "DC", "PB", "DDD", "DKM", "BP", "MCT", "RR"],
  63: ["LC", "MCR", "DC", "MCT", "DDD", "DDJ", "SL", "MB", "BC", "DKM", "PB", "YC", "WS", "WC", "BP", "RR"],
  64: ["LC", "WC", "DDD", "SL", "DDJ", "BC", "MB", "PB", "BP", "WS", "MCR", "MCT", "DKM", "YC", "DC", "RR"],
  65: ["LC", "DKM", "DDJ", "PB", "WS", "BP", "DDD", "DC", "BC", "MB", "WC", "MCT", "SL", "MCT", "YC", "RR"],
  66: ["LC", "WS", "PB", "MCT", "DDJ", "DKM", "BP", "DDD", "YC", "MCR", "WC", "MB", "DC", "SL", "BC", "RR"],
  67: ["LC", "YC", "BC", "SL", "PB", "DC", "BP", "WC", "MCT", "MCR", "DDJ", "WS", "MB", "DDD", "DKM", "RR"],
  68: ["LC", "DC", "DDJ", "BC", "DKM", "WC", "PB", "YC", "DDD", "WS", "BP", "SL", "MCR", "MB", "MCT", "RR"],
  69: ["LC", "SL", "WS", "WC", "DDJ", "YC", "MB", "PB", "DKM", "DDD", "MCT", "MCR", "BP", "BC", "DC", "RR"],
  70: ["LC", "DDD", "SL", "MCR", "MB", "WS", "BC", "MCT", "DKM", "BP", "WC", "DDJ", "PB", "YC", "DC", "RR"],
  71: ["LC", "PB", "SL", "WS", "DKM", "MB", "DDD", "DC", "WC", "DDJ", "BC", "MCR", "YC", "MCT", "BP", "RR"],
  72: ["LC", "MB", "MCR", "WC", "YC", "DC", "DDD", "BP", "BC", "WS", "DDJ", "MCT", "PB", "SL", "DKM", "RR"],
  73: ["LC", "BC", "DKM", "PB", "DDD", "SL", "YC", "MB", "WS", "MCR", "DC", "MCT", "BP", "WC", "DDJ", "RR"],
  74: ["LC", "MCR", "WS", "MCT", "YC", "DDD", "DDJ", "PB", "DKM", "SL", "WC", "DC", "BP", "MB", "BC", "RR"],
  75: ["LC", "WC", "SL", "DC", "MCR", "BP", "BC", "YC", "DDD", "WS", "MCT", "MB", "DKM", "PB", "DDJ", "RR"],
  76: ["LC", "DDJ", "YC", "WS", "MCR", "MCT", "BC", "DKM", "WC", "MB", "BP", "DDD", "PB", "SL", "DC", "RR"],
  77: ["LC", "WC", "DDD", "SL", "YC", "PB", "MCT", "BP", "MCR", "MB", "DKM", "WS", "DDJ", "BC", "DC", "RR"],
  78: ["LC", "DKM", "DC", "MCT", "BC", "MCR", "SL", "DDJ", "MB", "DDD", "BP", "WS", "PB", "WC", "YC", "RR"],
  79: ["LC", "MCR", "YC", "DDD", "DDJ", "PB", "WS", "DKM", "BC", "MB", "WC", "DC", "BP", "MCT", "SL", "RR"],
  80: ["LC", "WC", "PB", "BP", "DDJ", "YC", "WS", "SL", "MB", "MCR", "MCR", "DDD", "DC", "BC", "DKM", "RR"],
  81: ["LC", "BC", "WS", "YC", "DDD", "SL", "DKM", "PB", "MCT", "MB", "BP", "MCR", "DC", "WC", "DDJ", "RR"],
  82: ["LC", "MCT", "YC", "WS", "MCR", "DKM", "DDD", "MB", "PB", "DDJ", "BP", "DC", "SL", "WC", "BC", "RR"],
  83: ["LC", "DC", "PB", "MB", "WC", "YC", "MCT", "DDD", "MCR", "SL", "DKM", "WS", "BC", "BP", "DDJ", "RR"],
  84: ["LC", "SL", "PB", "MB", "BP", "YC", "BC", "WC", "DKM", "WS", "MCR", "MCT", "DDJ", "DC", "DDD", "RR"],
  85: ["LC", "SL", "DDD", "DC", "WS", "BC", "BP", "MCR", "WC", "PB", "MB", "YC", "DDJ", "DKM", "MCT", "RR"],
  86: ["LC", "WC", "DDJ", "PB", "MCT", "YC", "SL", "DDD", "MCR", "BC", "DKM", "WS", "DC", "MB", "BP", "RR"],
  87: ["LC", "MCT", "DKM", "BP", "YC", "DDD", "MB", "MCR", "BC", "PB", "WC", "WS", "DC", "DDJ", "SL", "RR"],
  88: ["LC", "WC", "MB", "SL", "MCR", "BC", "DDJ", "PB", "DC", "YC", "DKM", "WS", "BP", "MCT", "DDD", "RR"],
  89: ["LC", "MCR", "WS", "MCT", "PB", "MB", "DC", "DDD", "YC", "BP", "BC", "DDJ", "DKM", "WC", "SL", "RR"],
  90: ["LC", "WC", "MB", "DC", "WS", "PB", "DKM", "BC", "YC", "MCR", "DDD", "BP", "MCT", "SL", "DDJ", "RR"],
  91: ["LC", "MCR", "MCT", "DDD", "SL", "PB", "DDJ", "WS", "BP", "MB", "WC", "DKM", "DC", "YC", "BC", "RR"],
  92: ["LC", "PB", "DDJ", "BP", "YC", "MCR", "DC", "DDD", "MB", "DKM", "SL", "WS", "WC", "MCT", "BC", "RR"],
  93: ["LC", "BP", "DDD", "BC", "WC", "MB", "DKM", "YC", "WS", "SL", "DC", "PB", "MCT", "MCR", "DDJ", "RR"],
  94: ["LC", "DKM", "MCT", "WS", "DDD", "MCR", "BC", "PB", "MB", "BP", "DC", "SL", "YC", "DDJ", "WC", "RR"],
  95: ["LC", "MB", "SL", "BC", "DKM", "DC", "WC", "DDD", "YC", "MCR", "DDJ", "WS", "BP", "PB", "MCT", "RR"],
  96: ["LC", "MB", "WS", "DC", "MCT", "BC", "PB", "YC", "DDJ", "MCR", "DDD", "BP", "WC", "DKM", "SL", "RR"],
  97: ["LC", "YC", "MB", "PB", "DC", "BP", "MCT", "BC", "WC", "DDD", "SL", "WS", "DDJ", "DKM", "MCR", "RR"],
  98: ["LC", "PB", "MB", "MCR", "WS", "BP", "WC", "DDJ", "SL", "MCT", "BC", "DDD", "DKM", "DC", "YC", "RR"],
  99: ["LC", "WS", "BP", "DDJ", "PB", "DDD", "DC", "MCR", "MB", "SL", "WC", "MCT", "BC", "DKM", "YC", "RR"],
  100: ["LC", "BP", "YC", "DC", "DKM", "SL", "DDD", "PB", "MCT", "BC", "WS", "MCR", "DDJ", "MB", "WC", "RR"],
  101: ["LC", "DDJ", "WC", "DDD", "SL", "MCR", "DC", "DKM", "BC", "MCT", "YC", "WS", "PB", "BP", "MB", "RR"],
  102: ["LC", "DC", "MCR", "PB", "WS", "SL", "DKM", "YC", "BC", "WC", "BP", "MB", "MCT", "DDD", "DDJ", "RR"],
  103: ["LC", "MCR", "DKM", "MCT", "DDJ", "BP", "DC", "MB", "BC", "PB", "YC", "WS", "SL", "DDD", "WC", "RR"],
  104: ["LC", "YC", "PB", "DC", "WC", "DDD", "SL", "BC", "BP", "WS", "DDJ", "MCT", "MCR", "DKM", "MB", "RR"],
  105: ["LC", "MCR", "DDD", "DKM", "PB", "BP", "DC", "MB", "DDJ", "MCT", "BC", "WS", "YC", "SL", "WC", "RR"],
  106: ["LC", "BC", "MCR", "YC", "DKM", "DC", "BP", "DDD", "SL", "WC", "MCT", "PB", "DDJ", "MB", "WS", "RR"],
  107: ["LC", "DKM", "MCT", "PB", "DC", "WS", "BP", "DDD", "MB", "MCR", "SL", "YC", "WC", "DDJ", "BC", "RR"],
  108: ["LC", "SL", "YC", "PB", "WS", "BC", "DDJ", "DDD", "BP", "MB", "DKM", "WC", "DC", "MCR", "MCT", "RR"],
  109: ["LC", "DDD", "WC", "MCT", "MCR", "WS", "YC", "DDJ", "DKM", "SL", "BC", "MB", "DC", "PB", "BP", "RR"],
  110: ["LC", "WS", "PB", "BP", "DDD", "MCT", "DC", "MB", "BC", "DKM", "YC", "MCR", "WC", "DDJ", "SL", "RR"],
  111: ["LC", "DC", "BC", "YC", "MCR", "SL", "PB", "BP", "MB", "WC", "WS", "DDD", "DKM", "MCT", "DDJ", "RR"],
  112: ["LC", "MCR", "MB", "WS", "DC", "DKM", "MCT", "PB", "BP", "SL", "YC", "DDD", "WC", "DDJ", "BC", "RR"],
  113: ["LC", "DKM", "BP", "DDD", "MCT", "MCR", "BC", "PB", "DDJ", "MB", "DC", "WS", "WC", "SL", "YC", "RR"],
  114: ["LC", "WS", "DC", "PB", "DDJ", "DDD", "BC", "DKM", "YC", "MB", "SL", "MCR", "MCT", "WC", "BP", "RR"],
  115: ["LC", "DKM", "YC", "PB", "WS", "DDD", "BC", "MCR", "BP", "MB", "MCT", "SL", "DC", "DDJ", "WC", "RR"],
  116: ["LC", "DC", "MB", "WC", "DDJ", "DDD", "MCR", "SL", "YC", "WS", "BP", "PB", "DKM", "BC", "MCT", "RR"],
  117: ["LC", "WC", "PB", "DC", "DDJ", "SL", "WS", "BC", "BP", "MCR", "MB", "DDD", "YC", "DKM", "MCT", "RR"],
  118: ["LC", "DDJ", "PB", "MCR", "DKM", "DDD", "SL", "BP", "MB", "WS", "WC", "MCT", "BC", "DC", "YC", "RR"]
}

export const tracks = {
  "LC": "luigiCircuit",
  "PB": "peachBeach",
  "BP": "babyPark",
  "DDD": "dryDryDesert",
  "MB": "mushroomBridge",
  "MCR": "marioCircuit",
  "DC": "daisyCruiser",
  "WS": "waluigiStadium",
  "SL": "sherbetLand",
  "MCT": "mushroomCity",
  "YC": "yoshiCircuit",
  "DKM": "dkMountain",
  "WC": "warioColosseum",
  "DDJ": "dinoDinoJungle",
  "BC": "bowsersCastle",
  "RR": "rainbowRoad",
};

