course_ids = {
    0x21: "babyPark",
    0x22: "peachBeach",
    0x23: "daisyCruiser",
    0x24: "luigiCircuit",
    0x25: "marioCircuit",
    0x26: "yoshiCircuit",
    0x28: "mushroomBridge",
    0x29: "mushroomCity",
    0x2A: "waluigiStadium",
    0x2B: "warioColosseum",
    0x2C: "dinoDinoJungle",
    0x2D: "dkMountain",
    0x2F: "bowsersCastle",
    0x31: "rainbowRoad",
    0x32: "dryDryDesert",
    0x33: "sherbetLand",
}

course_index = {
    "luigiCircuit": 0,
    "peachBeach": 1,
    "babyPark": 2,
    "dryDryDesert": 3,
    "mushroomBridge": 4,
    "marioCircuit": 5,
    "daisyCruiser": 6,
    "waluigiStadium": 7,
    "sherbetLand": 8,
    "mushroomCity": 9,
    "yoshiCircuit": 10,
    "dkMountain": 11,
    "warioColosseum": 12,
    "dinoDinoJungle": 13,
    "bowsersCastle": 14,
    "rainbowRoad": 15,
}

karts = [
    "Red Fire",
    "Green Fire",
    "Heart Coach",
    "Bloom Coach",
    "Turbo Yoshi",
    "Turbo Birdo",
    "Goo-Goo Buggy",
    "Rattle Buggy",
    "Toad Kart",
    "Toadette Kart",
    "Koopa Dasher",
    "Para-Wing",
    "DK Jumbo",
    "Barrel Train",
    "Koopa King",
    "Bullet Blaster",
    "Wario Car",
    "Waluigi Racer",
    "Piranha Pipes",
    "Boo Pipes",
    "Parade Kart"
]