export const kartTiers = {
  topSpeed: [
    [9, 8],
    [7, 6],
    [5, 4, 3],
    [2, 1],
  ],
  offRoad: [[9], [8, 7], [6, 5], [4, 3], [2, 1]],
  acceleration: [[9], [8, 7], [6, 5], [4, 3], [2, 1]],
  weight: [[9], [8, 7], [6, 5, 4], [3, 2], [1]],
  miniTurbo: [[3], [2], [1]],
  width: [
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
    [9, 10],
  ],
  bounciness: [[1], [2], [3, 4], [5, 6], [7]],
};

export const kartStats = [
  {
    name: "Red Fire",
    ranks: {
      topSpeed: 5,
      offRoad: 5,
      acceleration: 4,
      weight: 5,
      miniTurbo: 2,
      width: 5,
      bounciness: 5,
    },
    stats: {},
  },
  {
    name: "Green Fire",
    ranks: {
      topSpeed: 7,
      offRoad: 4,
      acceleration: 3,
      weight: 4,
      miniTurbo: 2,
      width: 5,
      bounciness: 5,
    },
    stats: {},
  },
  {
    name: "Heart Coach",
    ranks: {
      topSpeed: 4,
      offRoad: 6,
      acceleration: 6,
      weight: 5,
      miniTurbo: 2,
      width: 4,
      bounciness: 2,
    },
    stats: {},
  },
  {
    name: "Bloom Coach",
    ranks: {
      topSpeed: 6,
      offRoad: 4,
      acceleration: 5,
      weight: 3,
      miniTurbo: 2,
      width: 4,
      bounciness: 2,
    },
    stats: {},
  },
  {
    name: "Turbo Yoshi",
    ranks: {
      topSpeed: 4,
      offRoad: 5,
      acceleration: 6,
      weight: 6,
      miniTurbo: 2,
      width: 6,
      bounciness: 6,
    },
    stats: {},
  },
  {
    name: "Turbo Birdo",
    ranks: {
      topSpeed: 6,
      offRoad: 4,
      acceleration: 4,
      weight: 7,
      miniTurbo: 2,
      width: 6,
      bounciness: 6,
    },
    stats: {},
  },
  {
    name: "Goo-Goo Buggy",
    ranks: {
      topSpeed: 1,
      offRoad: 9,
      acceleration: 9,
      weight: 2,
      miniTurbo: 3,
      width: 2,
      bounciness: 3,
    },
    stats: {},
  },
  {
    name: "Rattle Buggy",
    ranks: {
      topSpeed: 2,
      offRoad: 9,
      acceleration: 8,
      weight: 2,
      miniTurbo: 3,
      width: 2,
      bounciness: 3,
    },
    stats: {},
  },
  {
    name: "Toad Kart",
    ranks: {
      topSpeed: 3,
      offRoad: 9,
      acceleration: 7,
      weight: 2,
      miniTurbo: 3,
      width: 5,
      bounciness: 2,
    },
    stats: {},
  },
  {
    name: "Toadette Kart",
    ranks: {
      topSpeed: 1,
      offRoad: 9,
      acceleration: 9,
      weight: 2,
      miniTurbo: 3,
      width: 5,
      bounciness: 2,
    },
    stats: {},
  },
  {
    name: "Koopa Dasher",
    ranks: {
      topSpeed: 2,
      offRoad: 8,
      acceleration: 8,
      weight: 3,
      miniTurbo: 3,
      width: 3,
      bounciness: 6,
    },
    stats: {},
  },
  {
    name: "Para-Wing",
    ranks: {
      topSpeed: 1,
      offRoad: 8,
      acceleration: 9,
      weight: 3,
      miniTurbo: 3,
      width: 3,
      bounciness: 2,
    },
    stats: {},
  },
  {
    name: "DK Jumbo",
    ranks: {
      topSpeed: 8,
      offRoad: 2,
      acceleration: 2,
      weight: 8,
      miniTurbo: 1,
      width: 8,
      bounciness: 4,
    },
    stats: {},
  },
  {
    name: "Barrel Train",
    ranks: {
      topSpeed: 8,
      offRoad: 7,
      acceleration: 3,
      weight: 5,
      miniTurbo: 3,
      width: 1,
      bounciness: 1,
    },
    stats: {},
  },
  {
    name: "Koopa King",
    ranks: {
      topSpeed: 9,
      offRoad: 1,
      acceleration: 1,
      weight: 9,
      miniTurbo: 1,
      width: 10,
      bounciness: 4,
    },
    stats: {},
  },
  {
    name: "Bullet Blaster",
    ranks: {
      topSpeed: 8,
      offRoad: 1,
      acceleration: 4,
      weight: 1,
      miniTurbo: 3,
      width: 3,
      bounciness: 6,
    },
    stats: {},
  },
  {
    name: "Wario Car",
    ranks: {
      topSpeed: 7,
      offRoad: 3,
      acceleration: 3,
      weight: 7,
      miniTurbo: 1,
      width: 7,
      bounciness: 3,
    },
    stats: {},
  },
  {
    name: "Waluigi Racer",
    ranks: {
      topSpeed: 5,
      offRoad: 9,
      acceleration: 5,
      weight: 6,
      miniTurbo: 2,
      width: 8,
      bounciness: 7,
    },
    stats: {},
  },
  {
    name: "Piranha Pipes",
    ranks: {
      topSpeed: 8,
      offRoad: 7,
      acceleration: 2,
      weight: 9,
      miniTurbo: 1,
      width: 7,
      bounciness: 1,
    },
    stats: {},
  },
  {
    name: "Boo Pipes",
    ranks: {
      topSpeed: 2,
      offRoad: 9,
      acceleration: 8,
      weight: 9,
      miniTurbo: 1,
      width: 7,
      bounciness: 1,
    },
    stats: {},
  },
  {
    name: "Parade Kart",
    ranks: {
      topSpeed: 7,
      offRoad: 3,
      acceleration: 4,
      weight: 7,
      miniTurbo: 3,
      width: 9,
      bounciness: 5,
    },
    stats: {},
  },
];
